modLoader = "javafml"
loaderVersion = "[36,)"
license = "Code: Public Domain"
issueTrackerURL = "https://github.com/IriDark/Jerm/issues"
[[mods]]
modId = "jerm"
version = "${file.jarVersion}"
displayName = "Just Enough Repair Materials"
displayURL = "https://discord.gg/wWdXpwuPmK"
authors = "IriDark"
description = ""
[[dependencies.jerm]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.jerm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.jerm]]
modId = "jei"
mandatory = true
versionRange = "[15.20.0.105,)"
ordering = "AFTER"
side = "BOTH"
